//
// Test Bench Module CatRecognizer_lib.signed_mult_tb.signed_mult_tester
//
// Created:
//          by - MaorA.UNKNOWN (DESKTOP-8K7FTQN)
//          at - 15:17:29 13/11/2018
//
// Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
//
`resetall
`timescale 1ns/1ns

module signed_mult_tb;

// Local declarations
parameter M = 3;
parameter N = 3;

// Internal signal declarations
wire [M - 1:0]      A;
wire [N - 1:0]      B;
wire [(M + N) - 1:0] F;


signed_mult #(M,N) U_0(
   .A (A),
   .B (B),
   .F (F)
);

signed_mult_tester #(M,N) U_1(
   .A (A),
   .B (B),
   .F (F)
);

endmodule // signed_mult_tb


